spring:
  servlet:
    multipart:
      max-file-size: 100000000000
      max-request-size: 100000000000
  thymeleaf:
    excluded-view-names: jsp/*
    enabled: true
    encoding: utf-8
    check-template-location: true
    prefix: WEB-INF/templates/
    suffix: .html
    cache: false
    templateMode: HTML5
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
