spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
    cache:
      period: 0
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace